### ISSUE TITLE
Now Secure API uses url params

### ISSUE THREAD

**Issue by DamienBitrise** [sp3nx0r/bitrise-step-nowsecure-auto-analysis#1]
```
curl -H "Authorization: Bearer ${API_TOKEN}" -X POST \
    https://lab-api.nowsecure.com/build/?group=838929c6-73c8-11e8-a19d-27d57188d0f9 --data-binary @bin.apk
```

See: https://docs.nowsecure.com/auto/api/spec/#api-Applications-submitBuild

Need ?group= in script here: https://github.com/sp3nx0r/bitrise-step-nowsecure-auto-analysis/blob/master/step.sh#L8

**Comment by sp3nx0r** [comment]
Woops, stale issue. Closing since PR merged with fix
