### ISSUE TITLE
fix curl error

### ISSUE THREAD

**Issue by blawrenceSE** [sp3nx0r/bitrise-step-nowsecure-auto-analysis#5]
curl is having trouble, forcing it to HTTP 1.1 has corrected the problem previously. 

https://github.com/sp3nx0r/bitrise-step-nowsecure-auto-analysis/pull/4 should fix the issue

**Comment by sp3nx0r** [comment]
Thanks for the note, PR merged. Will knock off the other issues can cut a new step version
